export const ERROR = "ERROR";
export const CLEARE_TEXT = "CLEARE_TEXT";
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_PRODUCTS = "GET_PRODUCTS";

export const INCREMENT_PRODUCT_COUNTER = "INCREMENT_PRODUCT_COUNTER";
export const DECREMENT_PRODUCT_COUNTER = "DECREMENT_PRODUCT_COUNTER";
export const CLEAR_COUNT = "CLEAR_COUNT";

export const ADD_TO_CART = "ADD_TO_CART";
export const DECREMENT_TO_CART = "DECREMENT_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

export const ORDER_UPLOADED = "ORDER_UPLOADED";
